# Data Import
Import Zomato data from https://www.kaggle.com/himanshupoddar/zomato-bangalore-restaurants from Bangalore

In [38]:
import numpy as np
import pandas as pd
pd.set_option('display.max_rows', 20)

In [2]:
df = pd.read_csv("zomato.csv")

In [3]:
df.dtypes

url                            object
address                        object
name                           object
online_order                   object
book_table                     object
rate                           object
votes                           int64
phone                          object
location                       object
rest_type                      object
dish_liked                     object
cuisines                       object
approx_cost(for two people)    object
reviews_list                   object
menu_item                      object
listed_in(type)                object
listed_in(city)                object
dtype: object

In [4]:
len(df)

51717

# Data Importation and Cleaning

## 1) Data Deduplication
Convert duplicates to correctly formatted row based for 'listed_in(type)','listed_in(city)'

In [5]:
len(df)

51717

In [6]:
df.sort_values(by=['name','address'])

# #FeelTheROLL is in two cities, and need to delete the 'Sarjapur Road' which is the smaller location anyway

# #L-81 Cafe has different rows with delivery and dine-in for the listed_in type, but other rows for a HSR neighborhood, so the other neighborhoods should be deleted

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
4321,https://www.zomato.com/bangalore/feeltheroll-b...,"Opposite Mantri Commercio, Outer Ring Road, De...",#FeelTheROLL,No,No,3.4/5,7,+91 9108342079\r\n+91 9886117901,Bellandur,Quick Bites,NaN,Fast Food,200,"[('Rated 5.0', ""RATED\n Had an egg chicken ro...",[],Delivery,Bellandur
49511,https://www.zomato.com/bangalore/feeltheroll-b...,"Opposite Mantri Commercio, Outer Ring Road, De...",#FeelTheROLL,No,No,3.4 /5,7,+91 9108342079\n+91 9886117901,Bellandur,Quick Bites,NaN,Fast Food,200,"[('Rated 5.0', ""RATED\n Had an egg chicken ro...",[],Delivery,Sarjapur Road
10182,https://www.zomato.com/bangalore/l-81-cafe-hsr...,"Sector 6, HSR Layout, HSR",#L-81 Cafe,Yes,No,3.9/5,48,+91 9986210891,HSR,Quick Bites,Burgers,"Fast Food, Beverages",400,"[('Rated 4.0', 'RATED\n This little cafe is s...",[],Delivery,BTM
11096,https://www.zomato.com/bangalore/l-81-cafe-hsr...,"Sector 6, HSR Layout, HSR",#L-81 Cafe,Yes,No,3.9/5,48,+91 9986210891,HSR,Quick Bites,Burgers,"Fast Food, Beverages",400,"[('Rated 4.0', 'RATED\n This little cafe is s...",[],Dine-out,BTM
16606,https://www.zomato.com/bangalore/l-81-cafe-hsr...,"Sector 6, HSR Layout, HSR",#L-81 Cafe,Yes,No,3.9/5,48,+91 9986210891,HSR,Quick Bites,Burgers,"Fast Food, Beverages",400,"[('Rated 4.0', 'RATED\n This little cafe is s...",[],Delivery,HSR
17166,https://www.zomato.com/bangalore/l-81-cafe-hsr...,"Sector 6, HSR Layout, HSR",#L-81 Cafe,Yes,No,3.9/5,48,+91 9986210891,HSR,Quick Bites,Burgers,"Fast Food, Beverages",400,"[('Rated 4.0', 'RATED\n This little cafe is s...",[],Dine-out,HSR
28099,https://www.zomato.com/bangalore/l-81-cafe-hsr...,"Sector 6, HSR Layout, HSR",#L-81 Cafe,Yes,No,3.9/5,48,+91 9986210891,HSR,Quick Bites,Burgers,"Fast Food, Beverages",400,"[('Rated 4.0', 'RATED\n This little cafe is s...",[],Delivery,Koramangala 4th Block
29004,https://www.zomato.com/bangalore/l-81-cafe-hsr...,"Sector 6, HSR Layout, HSR",#L-81 Cafe,Yes,No,3.9 /5,48,+91 9986210891,HSR,Quick Bites,Burgers,"Fast Food, Beverages",400,"[('Rated 4.0', 'RATED\n This little cafe is s...",[],Dine-out,Koramangala 4th Block
30833,https://www.zomato.com/bangalore/l-81-cafe-hsr...,"Sector 6, HSR Layout, HSR",#L-81 Cafe,Yes,No,3.9 /5,48,+91 9986210891,HSR,Quick Bites,Burgers,"Fast Food, Beverages",400,"[('Rated 4.0', 'RATED\n This little cafe is s...",[],Delivery,Koramangala 5th Block
33627,https://www.zomato.com/bangalore/l-81-cafe-hsr...,"Sector 6, HSR Layout, HSR",#L-81 Cafe,Yes,No,3.9 /5,48,+91 9986210891,HSR,Quick Bites,Burgers,"Fast Food, Beverages",400,"[('Rated 4.0', 'RATED\n This little cafe is s...",[],Delivery,Koramangala 6th Block
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28992,https://www.zomato.com/bangalore/re-cess-hilto...,"Hilton Bangalore Embassy GolfLinks, Embassy Go...",re:cess - Hilton Bangalore Embassy GolfLinks,No,Yes,4.1 /5,146,080 66799999\r\r\n+91 7353759841,Domlur,"Casual Dining, Bar","Coffee, Cheesecake, Paratha, Hot Chocolate, Bi...","South Indian, North Indian, Continental, European","1,200","[('Rated 5.0', ""RATED\n A big thanks for the ...",[],Dine-out,Koramangala 4th Block
45985,https://www.zomato.com/bangalore/re-cess-hilto...,"Hilton Bangalore Embassy GolfLinks, Embassy Go...",re:cess - Hilton Bangalore Embassy GolfLinks,No,Yes,4.1 /5,146,080 66799999\n+91 7353759841,Domlur,"Casual Dining, Bar","Coffee, Cheesecake, Paratha, Hot Chocolate, Bi...","South Indian, North Indian, Continental, European","1,200","[('Rated 5.0', 'RATED\n Calm, peaceful and se...",[],Dine-out,Old Airport Road
46132,https://www.zomato.com/bangalore/re-cess-hilto...,"Hilton Bangalore Embassy GolfLinks, Embassy Go...",re:cess - Hilton Bangalore Embassy GolfLinks,No,Yes,4.1 /5,146,080 66799999\n+91 7353759841,Domlur,"Casual Dining, Bar","Coffee, Cheesecake, Paratha, Hot Chocolate, Bi...","South Indian, North Indian, Continental, European","1,200","[('Rated 5.0', 'RATED\n Calm, peaceful and se...",[],Pubs and bars,Old Airport Road
40800,https://www.zomato.com/bangalore/repeat-hub-ma...,"67/4, Bhoganahalli Road, JCR Layout, Panathur,...",repEAT Hub,No,No,NaN,0,+91 9742745677,Marathahalli,Quick Bites,NaN,"North Indian, South Indian, Juices",200,"[('Rated 5.0', 'RATED\n Cook has great experi...",[],Delivery,Marathahalli
41849,https://www.zomato.com/bangalore/repeat-hub-ma...,"67/4, Bhoganahalli Road, JCR Layout, Panathur,...",repEAT Hub,No,No,NaN,0,+91 9742745677,Marathahalli,Quick Bites,NaN,"North Indian, South Indian, Juices",200,"[('Rated 5.0', 'RATED\n Cook has great experi...",[],Dine-out,Marathahalli
9665,https://www.zomato.com/bangalore/scoolmeal-btm...,"197/293-3, 32nd Main, 1st Stage, BTM, Bangalore",sCoolMeal,No,No,NaN,0,+91 8971958284,BTM,"Takeaway, Delivery",NaN,"North Indian, South Indian, Chinese, Pizza",300,[],[],Delivery,BTM
27925,https://www.zomato.com/bangalore/scoolmeal-btm...,"197/293-3, 32nd Main, 1st Stage, BTM, Bangalore",sCoolMeal,No,No,NaN,0,+91 8971958284,BTM,"Takeaway, Delivery",NaN,"North Indian, South Indian, Chinese, Pizza",300,[],[],Delivery,Koramangala 4th Block
30405,https://www.zomato.com/bangalore/scoolmeal-btm...,"197/293-3, 32nd Main, 1st Stage, BTM, Bangalore",sCoolMeal,No,No,NaN,0,+91 8971958284,BTM,"Takeaway, Delivery",NaN,"North Indian, South Indian, Chinese, Pizza",300,[],[],Delivery,Koramangala 5th Block
33476,https://www.zomato.com/bangalore/scoolmeal-btm...,"197/293-3, 32nd Main, 1st Stage, BTM, Bangalore",sCoolMeal,No,No,NaN,0,+91 8971958284,BTM,"Takeaway, Delivery",NaN,"North Indian, South Indian, Chinese, Pizza",300,[],[],Delivery,Koramangala 6th Block
36216,https://www.zomato.com/bangalore/scoolmeal-btm...,"197/293-3, 32nd Main, 1st Stage, BTM, Bangalore",sCoolMeal,No,No,NaN,0,+91 8971958284,BTM,"Takeaway, Delivery",NaN,"North Indian, South Indian, Chinese, Pizza",300,[],[],Delivery,Koramangala 7th Block

In [29]:
len(df.drop_duplicates(subset =['name', 'address','listed_in(type)','listed_in(city)'])) # Basically all duplicates due to there fields

51628

In [27]:
len(df.drop_duplicates(subset =['name', 'address','listed_in(type)']))

20915

In [25]:
len(df.drop_duplicates(subset =['name', 'address','listed_in(city)']))

33506

In [20]:

# There are around 12,499 restaraunts in total
df.drop_duplicates(subset =['name', 'address'])

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari
5,https://www.zomato.com/bangalore/timepass-dinn...,"37, 5-1, 4th Floor, Bosco Court, Gandhi Bazaar...",Timepass Dinner,Yes,No,3.8/5,286,+91 9980040002\r\n+91 9980063005,Basavanagudi,Casual Dining,"Onion Rings, Pasta, Kadhai Paneer, Salads, Sal...",North Indian,600,"[('Rated 3.0', 'RATED\n Food 3/5\nAmbience 3/...",[],Buffet,Banashankari
6,https://www.zomato.com/bangalore/rosewood-inte...,"19/1, New Timberyard Layout, Beside Satellite ...",Rosewood International Hotel - Bar & Restaurant,No,No,3.6/5,8,+91 9731716688\r\n080 26740366,Mysore Road,Casual Dining,NaN,"North Indian, South Indian, Andhra, Chinese",800,"[('Rated 5.0', 'RATED\n Awesome food ??Great ...",[],Buffet,Banashankari
7,https://www.zomato.com/bangalore/onesta-banash...,"2469, 3rd Floor, 24th Cross, Opposite BDA Comp...",Onesta,Yes,Yes,4.6/5,2556,080 48653961\r\n080 48655715,Banashankari,"Casual Dining, Cafe","Farmhouse Pizza, Chocolate Banana, Virgin Moji...","Pizza, Cafe, Italian",600,"[('Rated 5.0', 'RATED\n I personally really l...",[],Cafes,Banashankari
8,https://www.zomato.com/bangalore/penthouse-caf...,"1, 30th Main Road, 3rd Stage, Banashankari, Ba...",Penthouse Cafe,Yes,No,4.0/5,324,+91 8884135549\r\n+91 9449449316,Banashankari,Cafe,"Pizza, Mocktails, Coffee, Nachos, Salad, Pasta...","Cafe, Italian, Continental",700,"[('Rated 3.0', ""RATED\n I had been to this pl...",[],Cafes,Banashankari
9,https://www.zomato.com/bangalore/smacznego-ban...,"2470, 21 Main Road, 25th Cross, Banashankari, ...",Smacznego,Yes,No,4.2/5,504,+91 9945230807\r\n+91 9743804471,Banashankari,Cafe,"Waffles, Pasta, Coleslaw Sandwich, Choco Waffl...","Cafe, Mexican, Italian, Momos, Beverages",550,"[('Rated 4.0', ""RATED\n Easy to locate\nVFM 3...",[],Cafes,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51607,https://www.zomato.com/bangalore/chime-sherato...,Sheraton Grand Bengaluru Whitefield Hotel & Co...,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,236,080 49652769,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,"2,500","[('Rated 4.0', 'RATED\n Nice and friendly pla...",[],Dine-out,Whitefield
51610,https://www.zomato.com/bangalore/the-nest-the-...,"ITPL Main Road, KIADB Export Promotion Industr...",The Nest - The Den Bengaluru,No,No,3.4 /5,13,+91 8071117272,"ITPL Main Road, Whitefield","Bar, Casual Dining",NaN,"Finger Food, North Indian, Continental","1,500","[('Rated 5.0', 'RATED\n Great ambience , look...",[],Dine-out,Whitefield
51611,https://www.zomato.com/bangalore/chung-wah-itp...,"Unit 04-01, 4th floor, Ascendas Park Square Ma...",Chung Wah,No,No,2.5 /5,73,+91 9535948061,"ITPL Main Road, Whitefield",Casual Dining,Manchow Soup,"Chinese, Momos",800,"[('Rated 1.0', 'RATED\n Food is not everythin...",[],Dine-out,Whitefield
51614,https://www.zomato.com/bangalore/nawabs-empire...,"107/PA, ITPL Main Road, Whitefield, Bangalore",Nawabs Empire,No,No,3.2 /5,5,+91 8123358857,"ITPL Main Road, Whitefield",Quick Bites,NaN,"North Indian, Chinese, Arabian, Momos",300,"[('Rated 1.0', 'RATED\n This place is not at ...",[],Dine-out,Whitefield
51620,https://www.zomato.com/bangalore/fujian-expres...,"Food Court, Ascendas Park Square Mall, Whitefi...",Fujian Express,Yes,No,3.8 /5,182,+91 7760075458\n+91 9591852291,"ITPL Main Road, Whitefield",Food Court,"Noodles, Chicken Noodle, Momos, American Chops...","Thai, Chinese, Momos",600,"[('Rated 4.0', 'RATED\n This restaurant speci...","['Schezawn Paneer Dry', 'Gobi Manchurian Dry',...",Dine-out,Whitefield
51627,https://www.zomato.com/bangalore/new-shalimar-...,"Near MVJ College, Channasandra Main Road, Oppo...",New Shalimar Hotel,No,No,NaN,0,+91 9739549643\n+91 7892657455,"ITPL Main Road, Whitefield",Quick Bites,NaN,North Indian,300,[],[],Dine-out,Whitefield
51628,https://www.zomato.com/bangalore/nook-aloft-be...,"Cessna Business Park, Sarjapur ÃÂÃÂÃÂÃÂ...",Nook - Aloft Bengaluru Cessna Business Park,No,Yes,4.2 /5,411,+91 9663517066\n+91 9686861135,Bellandur,Casual Dining,"Chicken Quesadilla, Naan, Breakfast Buffet, Ch...","North Indian, Continental, Asian","1,800","[('Rated 2.0', 'RATED\n Aloft has been design...",[],Dine-out,Whitefield
51632,https://www.zomato.com/bangalore/seeya-restaur...,"44, Kodigehalli to Hoodi Main Road, Mahadevapu...",SeeYa Restaurant,No,No,3.3 /5,4,+91 9164562939,KR Puram,Quick Bites,NaN,"North Indian, Kerala, Chinese",350,"[('Rated 4.0', 'RATED\n Good food, take bit t...",[],Dine-out,Whitefield
51677,https://www.zomato.com/bangalore/bhagini-2-whi...,"139/C1, Next To GR Tech Park, Pattandur Agraha...",Bhagini,No,No,2.5 /5,81,080 65951222,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",800,"[('Rated 4.0', 'RATED\n A fine place to chill...",[],Drinks & nightlife,Whitefield
51714,https://www.zomato.com/bangalore/plunge-sherat...,Sheraton Grand Bengaluru Whitefield Hotel & Co...,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,NaN,0,NaN,Whitefield,Bar,NaN,Finger Food,"2,000",[],[],Pubs and bars,Whitefield

## 2) Reformat Review

## 3) Reformat lists of Cuisines, Dish_liked, res_type

## 4) Reform Rate to a Float

## 5) Reformat as Boolean the Online_Order and Book_Table

# Export for Review in Excel

In [16]:
df.drop('reviews_list', axis = 1).to_csv('export_Zomato.csv') # CSV works when having dropped Review

# Basic EDA

In [12]:
list(df.columns)

['url',
 'address',
 'name',
 'online_order',
 'book_table',
 'rate',
 'votes',
 'phone',
 'location',
 'rest_type',
 'dish_liked',
 'cuisines',
 'approx_cost(for two people)',
 'reviews_list',
 'menu_item',
 'listed_in(type)',
 'listed_in(city)']

In [24]:
# Location
df[['location','cuisines']].groupby('location').count().sort_values('cuisines',ascending = False)

# BTM Neighborhood is real https://en.wikipedia.org/wiki/BTM_Layout

# HSR Neighborhood https://en.wikipedia.org/wiki/HSR_Layout

                       cuisines
location
BTM                        5124
HSR                        2523
Koramangala 5th Block      2504
JP Nagar                   2233
Whitefield                 2136
Indiranagar                2081
Jayanagar                  1926
Marathahalli               1843
Bannerghatta Road          1630
Bellandur                  1286
...                         ...
Hebbal                       14
North Bangalore              14
Kengeri                       9
Nagarbhavi                    9
Central Bangalore             8
West Bangalore                6
Yelahanka                     6
Jakkur                        3
Rajarajeshwari Nagar          2
Peenya                        1

[93 rows x 1 columns]

In [ ]:
# Aprox cost
df[['location','cuisines']].groupby('location').count().sort_values('cuisines',ascending = False)

# Clustering of Restaraunts

In [7]:
# Convert categorical to dummy variables

df_kmeans = df.drop_duplicates(subset =['name', 'address'])[['online_order','book_table','rest_type','cuisines']]

#for cat in ['online_order','book_table','rest_type','cuisines']:

x1 = pd.get_dummies(df_kmeans["online_order"],prefix='online_order',drop_first=True)
x2 = pd.get_dummies(df_kmeans["book_table"],prefix='book_table',drop_first=True)
x3 = pd.get_dummies(df_kmeans["rest_type"],prefix='rest_type',drop_first=True)
x4 = pd.get_dummies(df_kmeans["cuisines"],prefix='cuisines',drop_first=True)

df_kmeans = x1.merge(x2, left_index = True, right_index = True).merge(x3, left_index = True, right_index = True).merge(x4, left_index = True, right_index = True)
df_kmeans
#df_kmeans = pd.merge([x1,x2], axis=0, ignore_index=True)

,online_order_Yes,book_table_Yes,"rest_type_Bakery, Beverage Shop","rest_type_Bakery, Cafe","rest_type_Bakery, Dessert Parlor","rest_type_Bakery, Food Court","rest_type_Bakery, Kiosk","rest_type_Bakery, Quick Bites","rest_type_Bakery, Sweet Shop",rest_type_Bar,...,"cuisines_Turkish, Arabian, Fast Food, Desserts, Healthy Food, Salad","cuisines_Turkish, Arabian, Fast Food, Salad, Healthy Food, Desserts","cuisines_Turkish, Chinese","cuisines_Turkish, Desserts","cuisines_Turkish, Fast Food","cuisines_Turkish, Fast Food, Biryani, Chinese","cuisines_Turkish, Rolls",cuisines_Vietnamese,"cuisines_Vietnamese, Salad","cuisines_Vietnamese, Thai, Burmese, Japanese"
0,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51607,0,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
51610,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
51611,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
51614,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
51620,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
51627,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
51628,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
51632,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
51677,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
51714,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [13]:
# take first 10 features
df_small = df_kmeans.iloc[: ,[x for x in range(0,10)]]
df_small

,online_order_Yes,book_table_Yes,"rest_type_Bakery, Beverage Shop","rest_type_Bakery, Cafe","rest_type_Bakery, Dessert Parlor","rest_type_Bakery, Food Court","rest_type_Bakery, Kiosk","rest_type_Bakery, Quick Bites","rest_type_Bakery, Sweet Shop",rest_type_Bar
0,1,1,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0
5,1,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0
7,1,1,0,0,0,0,0,0,0,0
8,1,0,0,0,0,0,0,0,0,0
9,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
51607,0,1,0,0,0,0,0,0,0,1
51610,0,0,0,0,0,0,0,0,0,0
51611,0,0,0,0,0,0,0,0,0,0
51614,0,0,0,0,0,0,0,0,0,0
51620,1,0,0,0,0,0,0,0,0,0
51627,0,0,0,0,0,0,0,0,0,0
51628,0,1,0,0,0,0,0,0,0,0
51632,0,0,0,0,0,0,0,0,0,0
51677,0,0,0,0,0,0,0,0,0,0
51714,0,0,0,0,0,0,0,0,0,1

## TSNE Clustering

In [ ]:
X_embedded = TSNE(n_components=2).fit_transform(df_small)

In [55]:
# Looking at example

df_small[(df_small['rest_type_Bakery, Cafe'] == 1) | (df_small['rest_type_Bakery, Beverage Shop'] == 1)]

,online_order_Yes,book_table_Yes,"rest_type_Bakery, Beverage Shop","rest_type_Bakery, Cafe","rest_type_Bakery, Dessert Parlor","rest_type_Bakery, Food Court","rest_type_Bakery, Kiosk","rest_type_Bakery, Quick Bites","rest_type_Bakery, Sweet Shop",rest_type_Bar
3285,0,0,1,0,0,0,0,0,0,0
5048,1,0,0,1,0,0,0,0,0,0
5051,0,0,0,1,0,0,0,0,0,0
5905,0,0,1,0,0,0,0,0,0,0
5918,0,0,1,0,0,0,0,0,0,0
6796,0,0,0,1,0,0,0,0,0,0
6807,1,0,0,1,0,0,0,0,0,0
7136,1,1,0,1,0,0,0,0,0,0
8859,1,0,0,1,0,0,0,0,0,0
14616,1,0,0,1,0,0,0,0,0,0
14777,1,0,0,1,0,0,0,0,0,0
15846,0,0,0,1,0,0,0,0,0,0
17614,1,0,0,1,0,0,0,0,0,0
39716,1,0,0,1,0,0,0,0,0,0
40555,0,0,0,1,0,0,0,0,0,0
41183,1,0,0,1,0,0,0,0,0,0
50118,1,0,0,1,0,0,0,0,0,0

In [57]:
print(
    X_embedded[3285], # bev
    X_embedded[6796], # cafe
    X_embedded[5051], # cafe
    X_embedded[5905] # bev
)

[-0.93330204  9.577247  ] [ 0.16703182 -9.0995245 ] [0.87390083 9.215245  ] [  1.9668864 -10.572024 ]

## PCA Clustering

In [25]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
pca.fit(df_small)

PCA(copy=True, iterated_power='auto', n_components=2, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [26]:
pca

PCA(copy=True, iterated_power='auto', n_components=2, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [18]:
import matplotlib as plt
import seaborn as sns
#df_subset['tsne-2d-one'] = X_embedded[:,0]
#df_subset['tsne-2d-two'] = X_embedded[:,1]

#plt.figure(figsize=(16,10))
sns.scatterplot(
    x="tsne-2d-one", y="tsne-2d-two",
    hue="y",
    palette=sns.color_palette("hls", 10),
    data=X_embedded,
    legend="full",
    alpha=0.3
)

ModuleNotFoundError: No module named 'seaborn'

## KMeans Clustering

In [55]:
from sklearn.cluster import KMeans
import numpy as np
kmeans = KMeans(n_clusters=5, random_state=14).fit(df_kmeans)

In [56]:
kmeans

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=5, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=14, tol=0.0001, verbose=0)